// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePointsUserChange = "points_user_change"

// PointsUserChange 用户积分变动
type PointsUserChange struct {
	ID          int64  `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	UserID      int64  `gorm:"column:user_id;type:bigint;not null;comment:用户id" json:"userId"`                  // 用户id
	Username    string `gorm:"column:username;type:varchar(255);not null;comment:用户名称" json:"username"`         // 用户名称
	Integral    int64  `gorm:"column:integral;type:bigint;not null;comment:积分" json:"integral"`                 // 积分
	Type        int64  `gorm:"column:type;type:tinyint(1);not null;comment:状态: 1=增加,2=减少" json:"type"`          // 状态: 1=增加,2=减少
	Name        string `gorm:"column:name;type:varchar(255);not null;comment:奖励物品名称" json:"name"`               // 奖励物品名称
	AfterScore  int64  `gorm:"column:after_score;type:bigint;not null;comment:用户变动后积分" json:"afterScore"`       // 用户变动后积分
	CreatedAt   int64  `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                                 // 创建时间
	UpdatedAt   int64  `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`                                 // 更新时间
	UpdatedUser string `gorm:"column:updated_user;type:varchar(255);not null;comment:最后修改人" json:"updatedUser"` // 最后修改人
}

// TableName PointsUserChange's table name
func (*PointsUserChange) TableName() string {
	return TableNamePointsUserChange
}
