// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/shopspring/decimal"

const TableNameWinBetslipsDateStatistics = "win_betslips_date_statistics"

// WinBetslipsDateStatistics 打码量统计表，记录用户每日的打码量
type WinBetslipsDateStatistics struct {
	ID             int64           `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:自增主键" json:"id,string"`     // 自增主键
	UID            int64           `gorm:"column:uid;type:bigint unsigned;not null;comment:用户ID" json:"uid"`                               // 用户ID
	Username       string          `gorm:"column:username;type:varchar(255);not null;comment:用户名" json:"username"`                         // 用户名
	BetAmountCount decimal.Decimal `gorm:"column:bet_amount_count;type:decimal(18,2);not null;comment:打码量金额，保留两位小数" json:"betAmountCount"` // 打码量金额，保留两位小数
	Date           string          `gorm:"column:date;type:varchar(10);not null;comment:按天时间，格式为Y-m-d" json:"date"`                        // 按天时间，格式为Y-m-d
	CreatedAt      int64           `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                                                // 创建时间，Unix时间戳
	UpdatedAt      int64           `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`                                                // 更新时间，Unix时间戳
}

// TableName WinBetslipsDateStatistics's table name
func (*WinBetslipsDateStatistics) TableName() string {
	return TableNameWinBetslipsDateStatistics
}
