// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinSmsChannel = "win_sms_channel"

// WinSmsChannel mapped from table <win_sms_channel>
type WinSmsChannel struct {
	ID           int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	AppID        string `gorm:"column:app_Id;type:varchar(64)" json:"appId"`
	AppCode      string `gorm:"column:app_code;type:varchar(64)" json:"appCode"`
	APIKey       string `gorm:"column:api_key;type:varchar(255)" json:"apiKey"`
	APIPwd       string `gorm:"column:api_pwd;type:varchar(255)" json:"apiPwd"`
	APIURL       string `gorm:"column:api_url;type:varchar(255)" json:"apiUrl"`
	AppName      string `gorm:"column:app_name;type:varchar(255)" json:"appName"`
	Status       int64  `gorm:"column:status;type:tinyint;default:3;comment:1==禁用  3==启用" json:"status"` // 1==禁用  3==启用
	CreatedAt    int64  `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                         // 创建时间
	Remark       string `gorm:"column:remark;type:varchar(250);comment:备注" json:"remark"`                // 备注
	Operator     string `gorm:"column:operator;type:varchar(50);comment:操作人" json:"operator"`            // 操作人
	OperatorName string `gorm:"column:operator_name;type:varchar(32);comment:操作人姓名" json:"operatorName"` // 操作人姓名
	UpdatedAt    int64  `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`                         // 更新时间
}

// TableName WinSmsChannel's table name
func (*WinSmsChannel) TableName() string {
	return TableNameWinSmsChannel
}
